services:

  db:
    image: postgres:15-alpine
    container_name: liquibase-demo-db
    restart: always
    healthcheck:
      test: pg_isready -U postgres -d liquibase_demo
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./db-init/db-liquibase-demo.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - liquibase_demo_net

networks:
  liquibase_demo_net:
