spring:
  application:
    name: liquibase-demo
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/liquibase_demo}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: "!" # exclude all changelogs with context specified

logging:
  level:
    root: info
    liquibase: info
